name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Blockbench Version
      description: Run `blockbench version` to get version information
      placeholder: "v1.0.0 (or output from blockbench version)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version (if building from source)
      description: Run `go version` if you built from source
      placeholder: "go version go1.23.4 linux/amd64"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Run command: `blockbench install addon.mcaddon /server`
        2. See error: ...
        3. Expected: ...
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command that caused the issue
      placeholder: "blockbench install addon.mcaddon /path/to/server --verbose"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: Copy and paste any error messages or logs. Use `--verbose` flag for detailed output.
      render: shell
      placeholder: Paste error messages or verbose output here

  - type: textarea
    id: server-structure
    attributes:
      label: Server Directory Structure
      description: If relevant, show your server directory structure (you can use `tree` or `ls -la`)
      render: text
      placeholder: |
        server/
        ├── server.properties
        ├── development_behavior_packs/
        ├── development_resource_packs/
        └── worlds/
            └── myworld/

  - type: textarea
    id: addon-info
    attributes:
      label: Addon Information
      description: Information about the addon file you're trying to install (if relevant)
      placeholder: |
        - File type: .mcaddon/.mcpack
        - File size: 
        - Contains: behavior pack, resource pack, both
        - Source: where you got the addon

  - type: checkboxes
    id: tried-solutions
    attributes:
      label: Troubleshooting Steps Tried
      description: What have you tried to resolve this issue?
      options:
        - label: Used `--verbose` flag for detailed output
        - label: Used `--dry-run` to preview the operation  
        - label: Checked server.properties contains level-name
        - label: Verified server directory structure exists
        - label: Tried with a different addon file
        - label: Checked file permissions

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: Add any other context about the problem here